"""Shared constants for the Background Remover macOS GUI."""

DUPLICATE_FRAME_SIGNATURE_SIZE = (24, 24)
DUPLICATE_FRAME_MAX_MEAN_DIFFERENCE = 0.015
DEDUPLICATION_THRESHOLD_MIN = 0.001
DEDUPLICATION_THRESHOLD_MAX = 0.050
COLOR_CLEANUP_THRESHOLD_MIN = 0
COLOR_CLEANUP_THRESHOLD_MAX = 120
COLOR_CLEANUP_THRESHOLD_DEFAULT = 15
MAX_COLOR_CLEANUP_WORKERS = 4
MAX_PENDING_COLOR_CLEANUP_TASKS_PER_WORKER = 2
PROTECT_BRUSH_RADIUS_MIN = 2
PROTECT_BRUSH_RADIUS_MAX = 40
PROTECT_BRUSH_RADIUS_DEFAULT = 8
PROTECT_OVERLAY_COLOR = (100, 220, 255, 80)  # translucent cyan overlay on protected pixels
COLOR_PROTECT_THRESHOLD_MIN = 0
COLOR_PROTECT_THRESHOLD_MAX = 120
COLOR_PROTECT_THRESHOLD_DEFAULT = 15

PREVIEW_BASE_WIDTH = 250
PREVIEW_BASE_HEIGHT = 200
PREVIEW_ZOOM_MIN = 0.25
PREVIEW_ZOOM_MAX = 4.0
PREVIEW_ZOOM_STEP = 1.15
PREVIEW_MAX_DISPLAY_SIDE = 1800
COLOR_SWATCH_SIZE = 18
COLOR_SWATCH_MAX_VISIBLE = 12
